sudo: required
services:
  - docker

before_install:
  - docker build -t cagatayerdiz/docker-react -f .

script:
  - docker run -e CI=true cagatayerdiz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-286465718615"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY